"""Named factory bind for a research unit (D8 compose).

Generated by develop_desk_d8. Provenance URI is load-bearing.
"""

UNIT_ID = 'standard_ei_01_nist_ai_risk_management_framework'
DESTINATION = 'oss_feature'
PROVENANCE_URI = 'https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf'
TITLE = 'NIST AI Risk Management Framework (AI RMF 1.0)'
REUSE = 'dev_factory.units'
REUSE_NOTES = "Live reuse scan tokens=['standard', 'nist', 'risk', 'management', 'framework']; hits=16"


def bind_unit() -> dict:
    """Return the named bind for this unit (URI stays reviewable)."""
    if not PROVENANCE_URI:
        raise ValueError("bind missing provenance URI")
    return {
        "unit_id": UNIT_ID,
        "destination": DESTINATION,
        "provenance_uri": PROVENANCE_URI,
        "title": TITLE,
        "reuse": REUSE,
    }
